name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release'
        exclusions: ''

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: 'blender-dcltoolkit-scene-slicer.zip'
        token: ${{ secrets.GITHUB_TOKEN }}